// Mocks generated by Mockito 5.4.5 from annotations
// in tracking_app/test/features/auth/data/repositories_imp/auth_repository_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:tracking_app/core/network/common/api_result.dart' as _i4;
import 'package:tracking_app/features/auth/data/models/request/forget_request_dto.dart'
    as _i9;
import 'package:tracking_app/features/auth/data/models/request/login/login_request_dto.dart'
    as _i6;
import 'package:tracking_app/features/auth/data/models/response/forget_response_dto.dart'
    as _i8;
import 'package:tracking_app/features/auth/data/models/response/login/login_response_dto.dart'
    as _i5;
import 'package:tracking_app/features/auth/data/models/response/reset_password_request.dart'
    as _i12;
import 'package:tracking_app/features/auth/data/models/response/reset_password_response.dart'
    as _i11;
import 'package:tracking_app/features/auth/data/models/response/verify_code_request.dart'
    as _i10;
import 'package:tracking_app/features/auth/domain/data_sources/remote/remote_auth_data_source.dart'
    as _i2;
import 'package:tracking_app/features/auth/domain/entities/apply_entity.dart'
    as _i13;
import 'package:tracking_app/features/auth/domain/entities/vehicles_entitiy.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteAuthDataSource extends _i1.Mock
    implements _i2.RemoteAuthDataSource {
  MockRemoteAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.LoginResponseDto?>> login(
    _i6.LoginRequestDto? loginRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequest]),
            returnValue: _i3.Future<_i4.Result<_i5.LoginResponseDto?>>.value(
              _i7.dummyValue<_i4.Result<_i5.LoginResponseDto?>>(
                this,
                Invocation.method(#login, [loginRequest]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.LoginResponseDto?>>);

  @override
  _i3.Future<_i4.Result<_i8.ForgetResponseDto?>> forgetPassword(
    _i9.ForgetRequestDto? forgetRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetRequest]),
            returnValue: _i3.Future<_i4.Result<_i8.ForgetResponseDto?>>.value(
              _i7.dummyValue<_i4.Result<_i8.ForgetResponseDto?>>(
                this,
                Invocation.method(#forgetPassword, [forgetRequest]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.ForgetResponseDto?>>);

  @override
  _i3.Future<_i4.Result<String?>> verifyCode(
    _i10.VerifyCodeRequest? verifyCode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyCode, [verifyCode]),
            returnValue: _i3.Future<_i4.Result<String?>>.value(
              _i7.dummyValue<_i4.Result<String?>>(
                this,
                Invocation.method(#verifyCode, [verifyCode]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String?>>);

  @override
  _i3.Future<_i4.Result<_i11.ResetPasswordResponse?>> resetPassword(
    _i12.ResetPasswordRequest? resetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequest]),
            returnValue:
                _i3.Future<_i4.Result<_i11.ResetPasswordResponse?>>.value(
                  _i7.dummyValue<_i4.Result<_i11.ResetPasswordResponse?>>(
                    this,
                    Invocation.method(#resetPassword, [resetPasswordRequest]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i11.ResetPasswordResponse?>>);

  @override
  _i3.Future<_i4.Result<_i13.ApplyEntity>> apply(_i14.FormData? formData) =>
      (super.noSuchMethod(
            Invocation.method(#apply, [formData]),
            returnValue: _i3.Future<_i4.Result<_i13.ApplyEntity>>.value(
              _i7.dummyValue<_i4.Result<_i13.ApplyEntity>>(
                this,
                Invocation.method(#apply, [formData]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i13.ApplyEntity>>);

  @override
  _i3.Future<_i4.Result<_i15.VehiclesModelEntity>> getAllVehicles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllVehicles, []),
            returnValue: _i3.Future<_i4.Result<_i15.VehiclesModelEntity>>.value(
              _i7.dummyValue<_i4.Result<_i15.VehiclesModelEntity>>(
                this,
                Invocation.method(#getAllVehicles, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i15.VehiclesModelEntity>>);
}
