name: Validate Branch Name

on:
  push:
  pull_request:

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate branch name
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const regex = /^(feature|fix|chore|docs|refactor|test|style|perf)\/[a-z0-9-]+$/;

            if (!regex.test(branchName)) {
              core.setFailed(`Invalid branch name: "${branchName}"
Branch name must follow this format:
 <type>/<slug>
Examples:
  feature/login-page
  fix/api-timeout
  docs/readme-update`);
            } else {
              console.log("Branch name is valid.");
            }
