name: Validate PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR Title Verify
        uses: satvik-s/pr-title-check
        with:
          pattern: '^(fix|feat|chore|docs|style|refactor|perf|test)(\\([\\w\\-]+\\))?: .+$'
